name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache Node modules
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install semantic-release plugins
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install -D @semantic-release/changelog @semantic-release/git
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Agrega estas líneas modificándolas con tus datos
          GIT_AUTHOR_NAME: "Matt Garman"
          GIT_AUTHOR_EMAIL: "matt.garman@gmail.com"
          GIT_COMMITTER_NAME: "Matt Garman"
          GIT_COMMITTER_EMAIL: "matt.garman@gmail.com"
        run: npx semantic-release
